"""Integration tests for check_coverage module using real adapters."""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from pytest_test_categories.coverage.readers import CoveragePyReader
from tests._utils.check_coverage import (
    get_current_coverage,
    read_stored_coverage,
    store_coverage,
)
from tests._utils.file_system import RealFileSystem


@pytest.mark.medium
class DescribeCheckCoverageIntegration:
    """Integration tests for check_coverage module with real file system and coverage reader."""

    def it_stores_and_reads_coverage_with_real_file_system(self) -> None:
        """Store and read coverage values using real file system."""
        fs = RealFileSystem()

        # Store coverage (creates coverage_target.txt)
        test_coverage = 88.5
        store_coverage(fs, test_coverage)

        try:
            # Read it back
            result = read_stored_coverage(fs)

            assert result == test_coverage
        finally:
            # Clean up
            coverage_file = Path('coverage_target.txt')
            if coverage_file.exists():
                coverage_file.unlink()

    def it_reads_current_coverage_from_coverage_file(self) -> None:
        """Read current coverage from actual coverage.py file."""
        # This test requires a .coverage file to exist
        # We'll use the actual project's coverage file if it exists
        if not Path('.coverage').exists():
            pytest.skip('No .coverage file found')

        coverage_reader = CoveragePyReader()

        result = get_current_coverage(coverage_reader)

        # We don't know the exact coverage value, but it should be a valid percentage
        max_coverage = 100.0
        assert 0.0 <= result <= max_coverage

    def it_handles_custom_coverage_file_path(self) -> None:
        """Read coverage from a custom coverage file path."""
        with tempfile.TemporaryDirectory() as tmpdir:
            custom_coverage_file = Path(tmpdir) / '.coverage.custom'

            # Create a minimal coverage file (this would normally be generated by coverage.py)
            # For this test, we'll just verify the reader can be instantiated with custom path
            coverage_reader = CoveragePyReader(coverage_file=str(custom_coverage_file))

            # If file doesn't exist, it should return 0.0
            result = get_current_coverage(coverage_reader)

            assert result == 0.0
